---
 - hosts: localhost
   tasks:
     - name: transfer data from machine1 to machine2
       become: yes
       copy: src=/etc/yum.repos.d/nginx.repo dest=/etc/yum.repos.d/
       delegate_to: 192.168.56.11
